### ISSUE TITLE
Tracking: Test improvements

### ISSUE THREAD

**Issue by JeppeKlitgaard** [qim-center/qim3d#154]
Tracked issues and PRs:
- [ ] Test failures (see also below)
	- [ ] #115 
		- [X] #164 
		- [X] #165 
		- [X] #183
		- [X] #172 
- [ ] Clean up
	- [ ] #121 
	- [ ] #155
	- [X] #183 
	- [ ] #155 
		- [ ] #174
	- [X] #131 
- [ ] CI
	- [ ] #116 
		- [ ] #137  
	- [ ] ~~Blocker: #171~~
	- [ ] Blocker: #217 
- [ ] Tooling
	- [x] 	#184
	- [ ] #177 
- [ ] Other improvements
	- [ ] #182 
	- [ ] #179 

I encourage new hires (@SotirisTouliopoulos, @HeatherGeha) to try and fix some of these. You should check which ones already have open PRs (and link this issue in your PR for discoverability). Happy to help out with any issues you might have!

Status over currently failing test files:
- [x] [data_handling/generate_test.py](https://github.com/qim-center/qim3d/blob/main/qim3d/tests/data_handling/generate_test.py) @SotirisTouliopoulos
	- [X] #165 
- [ ] [docstrings/test_docstrings.py](https://github.com/qim-center/qim3d/blob/main/qim3d/tests/docstrings/test_docstrings.py)
	- [x] #183 
- [ ] [features/test_features.py](https://github.com/qim-center/qim3d/blob/main/qim3d/tests/features/test_features.py)
- [ ] [io/test_save.py](https://github.com/qim-center/qim3d/blob/main/qim3d/tests/io/test_save.py) @SotirisTouliopoulos 
- [ ] [morphology/test_morphology.py](https://github.com/qim-center/qim3d/blob/main/qim3d/tests/morphology/test_morphology.py) @victorcabre 
- [ ] [viz/test_img.py](https://github.com/qim-center/qim3d/blob/main/qim3d/tests/viz/test_img.py)

Status over currently failing tests (after #183 is merged):
- [x]  `qim3d/tests/data_handling/generate_test.py::test_data_not_fit_raises - TypeError: volume_collection() got an unexpected keyword argument 'num_volumes'` @SotirisTouliopoulos, #165 
- [x]  `qim3d/tests/data_handling/generate_test.py::test_data_single_fit_multiple_placements - TypeError: volume_collection() got an unexpected keyword argument 'num_volumes'` @SotirisTouliopoulos, #165 
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_generate[volume] - AttributeError: AxesImage.set() got an unexpected keyword argument 'value_min'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_generate[volume_collection] - AttributeError: AxesImage.set() got an unexpected keyword argument 'num_slices'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_generate[background] - TypeError: volume_collection() got an unexpected keyword argument 'num_volumes'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_viz[plot_connected_components] - AttributeError: module 'qim3d.segmentation' has no attribute 'get_3d_cc'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_viz[vector_field_3d] - AttributeError: module 'qim3d.examples' has no attribute 'fiber_150x256x256'. Did you mean: 'fly_150x256x256'?`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_viz[streamlines] - NameError: name 'volume' is not defined`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_features[mean_std_intensity] - AttributeError: AxesImage.set() got an unexpected keyword argument 'color_bar'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_filters[sobel] - AttributeError: AxesImage.set() got an unexpected keyword argument 'num_slices'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_segmentation[watershed] - AttributeError: AxesImage.set() got an unexpected keyword argument 'color_map'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_operations[remove_background] - AttributeError: AxesImage.set() got an unexpected keyword argument 'value_min'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_processing[local_thickness] - TypeError: volume_collection() got an unexpected keyword argument 'num_volumes'`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_processing[get_lines] - NameError: name 'qim3d' is not defined`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_ml[prepare_dataloaders] - NameError: name 'train_set' is not defined`
- [ ]  `qim3d/tests/docstrings/test_docstrings.py::test_docstrings_ml[model_summary] - NameError: name 'train_loader' is not defined`
- [ ]  `qim3d/tests/features/test_features.py::test_area - AssertionError: Area from volume and mesh should be equal`
- [ ]  `qim3d/tests/features/test_features.py::test_volume - AssertionError: Volume from volume and mesh should be equal`
- [ ]  `qim3d/tests/features/test_features.py::test_size - AssertionError: Size from volume and mesh should be equal`
- [ ]  `qim3d/tests/features/test_features.py::test_roughness - AssertionError: Roughness from volume and mesh should be equal`
- [ ]  `qim3d/tests/io/test_save.py::test_nifti_save_load - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jeppe\\AppData\\Local\\Temp\\tmpego8a7le\\test_im...`
- [ ]  `qim3d/tests/morphology/morphology_test.py::test_dilate - ValueError: Unknown closing method.`
- [ ]  `qim3d/tests/morphology/morphology_test.py::test_erode - ValueError: Unknown closing method.`
- [ ]  `qim3d/tests/morphology/morphology_test.py::test_opening - ValueError: Unknown closing method.`
- [ ]  `qim3d/tests/morphology/morphology_test.py::test_closing - ValueError: Unknown closing method.`
- [ ]  `qim3d/tests/morphology/morphology_test.py::test_black_tophat - ValueError: Unknown closing method.`
- [ ]  `qim3d/tests/morphology/morphology_test.py::test_white_tophat - ValueError: Unknown closing method.`
- [ ]  `qim3d/tests/viz/test_img.py::test_grid_overview - TypeError: grid_overview() got an unexpected keyword argument 'num_images'`
- [ ]  `qim3d/tests/viz/test_img.py::test_grid_overview_tuple - TypeError: grid_overview() got an unexpected keyword argument 'num_images'`
- [ ]  `qim3d/tests/viz/test_img.py::test_slices_numpy_array_input - AttributeError: AxesImage.set() got an unexpected keyword argument 'num_slices'`
- [ ]  `qim3d/tests/viz/test_img.py::test_slices_interpolation_option - AttributeError: AxesImage.set() got an unexpected keyword argument 'num_slices'`
- [ ]  `qim3d/tests/viz/test_img.py::test_slices_multiple_slices - AttributeError: AxesImage.set() got an unexpected keyword argument 'num_slices'`
- [ ]  `qim3d/tests/viz/test_img.py::test_slices_axis_argument - AttributeError: AxesImage.set() got an unexpected keyword argument 'num_slices'`
- [ ]  `qim3d/tests/viz/test_img.py::test_orthogonal_with_different_parameters - TypeError: got an unexpected keyword argument 'color_map'`
- [ ]  `qim3d/tests/viz/test_img.py::test_orthogonal_initial_slider_value - AssertionError: assert 4 == (10 // 2)`

**Comment by JeppeKlitgaard** [comment]
Currently as of eb9f197c4d015645c4530becc73d3b1cdf7da442:  **46 failed, 180 passed**

**Comment by JeppeKlitgaard** [comment]
36 failed, 217 passed in 644.12s (0:10:44) 🎉

**Comment by JeppeKlitgaard** [comment]
@SotirisTouliopoulos I think the `test_docstrings` is too large of a chunk to take on by yourself, and additionally it requires some fairly advanced magic mockery changes to be made in order to accommodate #174, #177, #155, so I have removed your claim on it for now. I am working on some changes that should be implemented first in order to make the rest of the clean-up a bit easier, but you are very very welcome to fix some of the failing doctests that don't relate to mocking and the issues I listed here.

**Edit 2026-08-26: the doctests are now easier to work on after #183 has been merged. Anyone looking to improve the doctests might benefit from taking a look at the PR to understand how mocking is done in doctests.**

**Comment by victorcabre** [comment]
With #242, only these fail:
```
FAILED qim3d/tests/gui/test_annotation_tool.py::test_app_launch - assert False is True
FAILED qim3d/tests/io/test_downloader.py::test_download - UnboundLocalError: cannot access local variable 'html_content' where it is not associated with a value
FAILED qim3d/tests/io/test_downloader.py::test_get_file_size - urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
FAILED qim3d/tests/io/test_downloader.py::test_extract_html - UnboundLocalError: cannot access local variable 'html_content' where it is not associated with a value

 4 failed, 242 passed in 336.37s (0:05:36)
```

**Comment by JeppeKlitgaard** [comment]
> With [#242](https://github.com/qim-center/qim3d/pull/242), only these fail:
> 
> ```
> FAILED qim3d/tests/gui/test_annotation_tool.py::test_app_launch - assert False is True
> FAILED qim3d/tests/io/test_downloader.py::test_download - UnboundLocalError: cannot access local variable 'html_content' where it is not associated with a value
> FAILED qim3d/tests/io/test_downloader.py::test_get_file_size - urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
> FAILED qim3d/tests/io/test_downloader.py::test_extract_html - UnboundLocalError: cannot access local variable 'html_content' where it is not associated with a value
> 
>  4 failed, 242 passed in 336.37s (0:05:36)
> ```

The `UnboundLocalError` is from some code that just is not sound. I think that code should not catch the error at all. The `UnboundLocalError` is raised because of some other error that gets eaten and thrown away before running into the unsound code. Maybe you can have a stab at that in a PR?

I can't reproduce these errors, so maybe there is some networking stuff going on. Worthy of further investigation, I guess.

**Comment by JeppeKlitgaard** [comment]
With #242 merged we now pass tests for me locally. There are a few problems still, namely CI crashing with a segmentation fault/access violation which means we can't test in CI, some tests requiring a qim server endpoint to be up, MacOS support and PyGEL3D causing CI to blow up as well.

I also suspect that there are some docstring tests that might not be run currently, see #177

**Comment by victorcabre** [comment]
> > With [#242](https://github.com/qim-center/qim3d/pull/242), only these fail:
> > ```
> > FAILED qim3d/tests/gui/test_annotation_tool.py::test_app_launch - assert False is True
> > FAILED qim3d/tests/io/test_downloader.py::test_download - UnboundLocalError: cannot access local variable 'html_content' where it is not associated with a value
> > FAILED qim3d/tests/io/test_downloader.py::test_get_file_size - urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
> > FAILED qim3d/tests/io/test_downloader.py::test_extract_html - UnboundLocalError: cannot access local variable 'html_content' where it is not associated with a value
> > 
> >  4 failed, 242 passed in 336.37s (0:05:36)
> > ```
> 
> The `UnboundLocalError` is from some code that just is not sound. I think that code should not catch the error at all. The `UnboundLocalError` is raised because of some other error that gets eaten and thrown away before running into the unsound code. Maybe you can have a stab at that in a PR?
> 
> I can't reproduce these errors, so maybe there is some networking stuff going on. Worthy of further investigation, I guess.

It was indeed a network issue. The tests pass. Regardless these tests will have to be removed with #250 

There's also this one: test_app_launch, which still seems to fail sometimes for me. I'll take a look at it.
